typography_spectrum: 0.30312109156511724
color:
  brandStrength: 0.44778841617517173
  lightness: 0.6365639332216233
  saturation: 0.1359862897079438
  rhythmicContrast: 0.7335114262532443
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/871deeb4-8935-4a6f-802a-939f0adc9999.png
layout_spectrum: 0.6904499910306185
analytics:
  google: UA-81928828-1
  facebook: '1193980147299469'
author:
  name: Andrew MacIntosh
  email: theprimatecast@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3a0cced3-44fe-45dc-a7d0-8caed1159938.png
name: The PrimateCast
navigation:
  - name: The PrimateCast @ CICASP
    url: 'http://www.cicasp.pri.kyoto-u.ac.jp/news/podcasts'
    type: external
  - name: Introducing The PrimateCast
    id: b6cc676a-fb9e-45ee-ab73-44da539d2ed1
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca89a89f-ee40-41b0-8895-2ea956193807.png
title: 'Ladies and Gentlemen, Welcome to The PrimateCast'
description: a podcast dedicated to the study and conservation of primates
