typography_spectrum: 0.29562222165986896
color:
  brandStrength: 0.017263787100091577
  lightness: 0.23749575670808554
  saturation: 0.9096645524259657
  rhythmicContrast: 0.10368687775917351
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/871deeb4-8935-4a6f-802a-939f0adc9999.png
layout_spectrum: 0.7111119222827256
author:
  name: Andrew MacIntosh
  email: theprimatecast@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3a0cced3-44fe-45dc-a7d0-8caed1159938.png
name: The PrimateCast
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca89a89f-ee40-41b0-8895-2ea956193807.png
title: 'Ladies and Gentlemen, The PrimateCast'
description: a podcast dedicated to the study and conservation of primates
